[package]
name = "HimalayanTOK_Nepali_64K"
version = "0.1.0"
edition = "2021"               # stable edition

[lib]
name = "HimalayanTOK_Nepali_64K"
crate-type = ["cdylib"]

[dependencies]
unicode-normalization = "0.1"
pyo3 = { version = "0.23", features = ["extension-module"] }
# Add any other dependencies your NepBPE.rs uses